### ISSUE TITLE
Conflicts with force-client-settings module

### ISSUE THREAD

**Issue by Weissrolf** [ironmonk88/monks-player-settings#8] opened 2022-07-31 11:56 UTC
Ahoi.

Short FYI: running your module with the force-clients-settings module causes problems (clicking on a force-client-setting icon closes the settings window and UI elements of other modules might get displaced).

https://gitlab.com/kimitsu_desu/force-client-settings

**Comment by ironmonk88** [comment] 2022-12-04 19:29
Duplicate of #5

**Closed by ironmonk88** 2022-12-04 19:29 UTC
Labels: duplicate
