### ISSUE TITLE
MonksSettingsConfig Console Error

### ISSUE THREAD

**Issue by Armandeus66** [ironmonk88/monks-player-settings#10] opened 2022-09-27 03:55 UTC
I don't know what this is affecting, but I get this error in the console several times a session. It mentions MonksSettingsConfig.

Error: You are accessing BasePackage#data which is now deprecated in favor of referencing schema fields directly on the BasePackage instance.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1685:19)
    at get data [as data] (commons.js:11720:7)
    at aaAutoRecognition.getData (auto-recognition.js:45:64)
    at aaAutoRecognition._render (foundry.js:5067:29)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Application.prototype._render#remote-highlight-ui (hooks.js:32:24)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Application.prototype._render#0 (libWrapper-wrapper.js:189:20)
    at aaAutoRecognition._render (foundry.js:5780:17)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁FormApplication.prototype._render#remote-highlight-ui (hooks.js:29:14)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁FormApplication.prototype._render#0 (libWrapper-wrapper.js:189:20)
    at aaAutoRecognition.render (foundry.js:5026:10)
    at MonksSettingsConfig._onClickSubmenu (foundry.js:71156:16)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

**Please complete as much of the following information as possible:**
 - Browser Chrome
 - Foundry Version v10.286
 - System Pathfinder 2e v4.1.3
 - Module version 1.0.6

**Comment by ironmonk88** [comment] 2022-12-04 19:20
It mentions MonksSettingConfig because Monks Settings steps in between the default settings config and the rest of the modules.
I don't believe the issue is with Monk's Player Settings, but with whatever module is causing the issue, and it's just flagging MPS because technically the code is passed through MPS.

I'd suggest running Find the Culprit to track down which module is causing the issues.

**Comment by ironmonk88** [comment] 2023-10-08 20:15
Closing this as it's unrelated to Player Settings

**Closed by ironmonk88** 2023-10-08 20:15 UTC
Labels: question
